import { getWorkspace } from '@/lib/workspaces';
import { createClient } from '@/lib/supabase/server';
import { aiConfigured } from '@/lib/ai/openrouter';
import { RevokeConnection } from '@/components/mcp-forms';
export const dynamic='force-dynamic';
export default async function Integrations() {
 const {user}=await getWorkspace(); const db=await createClient();
 const {data:connections,error}=await db.from('mcp_connections').select('client_id,client_name,workspace_id,created_at').eq('user_id',user.id);
 return <><div className="page-heading"><div><p className="eyebrow">CONNECTED WORK</p><h1>AI & connections</h1><p className="subtitle">Review AI drafts in the app, or retrieve your permitted actions from an MCP client.</p></div></div><div className="side-stack"><section className="panel"><h2>OpenRouter</h2><p>{aiConfigured()?'AI drafting is enabled.':'AI drafting needs an OpenRouter key from your app administrator.'}</p><p>Open any meeting to paste notes, extract drafts, then review and save. Open an unfinished action to draft a reminder. Notes or action details submitted for AI go to OpenRouter and its model provider.</p></section><section className="panel"><h2>Connect ChatGPT Work or Cowork</h2><label>MCP server URL<input readOnly value="https://ea-action-tracker.vercel.app/mcp"/></label><ol><li>Add a remote MCP connection in your client and paste this URL.</li><li>Choose OAuth authentication and sign in with your Action Tracker account.</li><li>Select a workspace and approve read access.</li><li>Ask: “Which actions are overdue, and who should I chase first?”</li></ol><p className="muted">Connection availability depends on your client and workspace administrator. Supabase OAuth and the access-token hook must be enabled first.</p></section><section className="panel"><h2>Your approved connections</h2>{error?<p className="form-error">Connection storage is not configured yet. Ask the administrator to apply migration 0003.</p>:!connections?.length?<p>No approved connections yet.</p>:connections.map(c=><div key={c.client_id}><h3>{c.client_name}</h3><p className="muted">Workspace: {c.workspace_id}</p><RevokeConnection clientId={c.client_id}/></div>)}</section></div></>;
}
